# Generated by Django 5.1.1 on 2024-10-06 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=10)),
                ('language_code', models.CharField(max_length=5)),
                ('num_pages', models.IntegerField()),
                ('ratings_count', models.IntegerField()),
                ('ratings_avg', models.FloatField()),
                ('reviews_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('account_date', models.DateTimeField()),
                ('num_books', models.IntegerField()),
                ('num_reviews', models.IntegerField()),
                ('num_friends', models.IntegerField()),
                ('books', models.ManyToManyField(to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='Date of Review')),
                ('rating', models.IntegerField(default=5)),
                ('review_text', models.CharField(max_length=1000)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(default='DeletedUser', on_delete=django.db.models.deletion.SET_DEFAULT, to='books.user')),
            ],
        ),
    ]
