# Generated by Django 5.1.1 on 2024-10-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_navbar_book_num_hits_book_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='users', to='books.book'),
        ),
    ]
