# Generated by Django 5.1.1 on 2024-10-11 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_user_is_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Navbar',
        ),
    ]
